# Generated by Django 3.1.13 on 2021-08-16 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('verse', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('version', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
