# Generated by Django 3.1.13 on 2021-08-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='verses.verse'),
        ),
    ]
